### ISSUE TITLE
Autoplay does not work on Android

### ISSUE THREAD

**Issue by larryaubstore** [googleads/googleads-ima-html5#4] opened 2015-12-01 01:42 UTC
To reproduce the bug:

- Take the playlist example.
- Load the page on android device.
- Click on the second item of the play.

Result: The companion loads but the video ad does not start. 

I did the same on IOS devices and it's work properly. 

My guess is that video tag did not receive the authorization to play on Android, maybe because IMA use two tags videos on Android and only one tag on IOS.

**Comment by shawnbuso** [comment] 2015-12-07 19:45
Thanks for the info - it looks like the problem is that we're not properly initializing the ad display container when the first video starts as a result of clicking on that thumbnail. I've got a fix in the works and it should be released soon.

**Comment by larryaubstore** [comment] 2015-12-08 02:46
I just sent you a pull request that fix the issue: https://github.com/googleads/googleads-ima-html5/pull/5

**Comment by shawnbuso** [comment] 2015-12-08 15:52
Hi Larry,

This issue has been fixed as of our latest GitHub push (tagged 2.3). If you're still seeing the problem with the updated code let me know.

Thanks!
Shawn

**Comment by larryaubstore** [comment] 2015-12-09 02:09
Super ! Thank you.

**Closed** 2016-01-12 20:52 UTC
